name: Compilar Executavel com PyArmor e PyInstaller

on:
  push:
    branches:
      - main

jobs:

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11.8'

      - name: Instalar Dependencias
        run: python -m pip install -r requirements.txt

      - name: Instalar PyArmor
        run: python -m pip install pyarmor

      - name: Instalar PyInstaller
        run: python -m pip install git+https://github.com/edvitor13/pyinstaller
      
      - name: Obfuscar Código com PyArmor
        run: cd .. && pyarmor gen -O dist gustavotube

      - name: Mover .PyInstaller/main_pyarmor.spec para Diretorio PyArmor
        run: cd .. && cp -r gustavotube/.pyinstaller/main_pyarmor.spec dist/gustavotube

      - name: Mover .PyInstaller para Diretorio PyArmor
        run: cd .. && cp -r gustavotube/.pyinstaller dist/gustavotube

      - name: Mover RunTime Pyarmor para Diretorio PyArmor
        run: cd .. && cp -r dist/pyarmor_runtime_000000 dist/gustavotube
      
      - name: Gerar executável com PyInstaller
        run: cd .. && cd dist/gustavotube && pyinstaller main_pyarmor.spec

      - name: Mover Executável para Diretorio Raiz
        run: cd .. && cp -r dist/gustavotube/dist gustavotube

      - name: Uploadar Executavel
        uses: actions/upload-artifact@v4
        with:
          name: GustavoTube.exe
          path: dist/GustavoTube.exe

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11.8'

      - name: Instalar Dependencias
        run: python -m pip install -r requirements.txt

      - name: Instalar PyArmor
        run: python -m pip install pyarmor

      - name: Instalar PyInstaller
        run: python -m pip install git+https://github.com/edvitor13/pyinstaller
      
      - name: Obfuscar Código com PyArmor
        run: cd .. && pyarmor gen -O dist gustavotube

      - name: Mover .PyInstaller/main_pyarmor.spec para Diretorio PyArmor
        run: cd .. && cp -r gustavotube/.pyinstaller/main_pyarmor.spec dist/gustavotube

      - name: Mover .PyInstaller para Diretorio PyArmor
        run: cd .. && cp -r gustavotube/.pyinstaller dist/gustavotube

      - name: Mover RunTime Pyarmor para Diretorio PyArmor
        run: cd .. && cp -r dist/pyarmor_runtime_000000 dist/gustavotube
      
      - name: Gerar executável com PyInstaller
        run: cd .. && cd dist/gustavotube && pyinstaller main_pyarmor.spec

      - name: Mover Executável para Diretorio Raiz
        run: cd .. && cp -r dist/gustavotube/dist gustavotube

      - name: Uploadar Executavel
        uses: actions/upload-artifact@v4
        with:
          name: GustavoTube-macOS
          path: dist/GustavoTube
  
  build-macos-12:
    runs-on: macos-12

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.11.8'

      - name: Instalar Dependencias
        run: python -m pip install -r requirements.txt

      - name: Instalar PyArmor
        run: python -m pip install pyarmor

      - name: Instalar PyInstaller
        run: python -m pip install git+https://github.com/edvitor13/pyinstaller
      
      - name: Obfuscar Código com PyArmor
        run: cd .. && pyarmor gen -O dist gustavotube
      
      - name: Mover .PyInstaller/main_pyarmor.spec para Diretorio PyArmor
        run: cd .. && cp -r gustavotube/.pyinstaller/main_pyarmor.spec dist/gustavotube

      - name: Mover .PyInstaller para Diretorio PyArmor
        run: cd .. && cp -r gustavotube/.pyinstaller dist/gustavotube

      - name: Mover RunTime Pyarmor para Diretorio PyArmor
        run: cd .. && cp -r dist/pyarmor_runtime_000000 dist/gustavotube
      
      - name: Gerar executável com PyInstaller
        run: cd .. && cd dist/gustavotube && pyinstaller main_pyarmor.spec

      - name: Mover Executável para Diretorio Raiz
        run: cd .. && cp -r dist/gustavotube/dist gustavotube

      - name: Uploadar Executavel
        uses: actions/upload-artifact@v4
        with:
          name: GustavoTube-macOS-12
          path: dist/GustavoTube

  release:
    name: release
    runs-on: ubuntu-latest
    needs: [build-windows, build-macos, build-macos-12]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download Windows rtifact
        uses: actions/download-artifact@v4
        with:
          name: GustavoTube.exe

      - name: Download MacOS artifact
        uses: actions/download-artifact@v4
        with:
          name: GustavoTube-macOS

      - name: Download MacOS 12 artifact
        uses: actions/download-artifact@v4
        with:
          name: GustavoTube-macOS-12

      - name: Extrair versão
        id: extract_version
        run: |
          versao=$(grep -oP '^__version__.*?"\K[^"]+' gustavotube/__init__.py)
          echo "Versão extraída: $versao"
          echo "VERSION=$versao" >> $GITHUB_ENV
        shell: bash

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        with:
          tag_name: v${{env.VERSION}} # ${{ github.ref }}
          draft: false
          prerelease: false
          files: |
            GustavoTube.exe
            GustavoTube-macOS
            GustavoTube-macOS-12

      - name: Notificação Discord - Sucesso
        uses: sarisia/actions-status-discord@v1.9.0
        if: success() # Executa apenas se não houver erros
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "GustavoTube v${{env.VERSION}} Lançado!"
          description: "Buildado e disponível no Github!\nhttps://github.com/edvitor13/gustavotube/releases/tag/v${{env.VERSION}}"
          username: GitHub Actions

      - name: Notificação Discord - Falha no download de artefatos
        uses: sarisia/actions-status-discord@v1.9.0
        if: failure() # Executa apenas se ocorrer falha
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          title: "❌ Falha no lançamento da versão do GustavoTube"
          description: "Ocorreu uma falha ao baixar os artefatos. Verifique os logs de execução para mais detalhes."
          username: GitHub Actions